"""
Report Formatter Agent
=======================

Part of the Agent Command Center (ACC) pipeline.

This agent sits downstream of the Writer Agent. It takes whatever
markdown the Writer Agent (or any other upstream agent) produced and
turns it into a single, canonical Mission Report.

It is a DETERMINISTIC agent, not an AI agent: it never calls a model,
never invents content, and never changes the meaning of a report. It
only reorganizes, deduplicates, and normalizes what it is given.

Pipeline
--------
    Raw AI Markdown
        -> _clean()                 strip noise, protect code blocks
        -> _extract_sections()      parse headings + bodies
        -> _remove_duplicate_sections()
        -> _normalize_sections()    map to canonical section names
        -> _build_report()          assemble canonical markdown
        -> _validate()              sanity-check the result
    Final Markdown

Public entry points
--------------------
- ReportFormatterAgent().format(mission, raw_markdown) -> ReportResult
- ReportFormatterAgent().handle(task) -> dict            (agent-message style)
- format_report(mission, summary, findings, recommendations) -> str
  (legacy-compatible shim for callers that still pass the report in
  four separate pieces instead of one raw markdown blob)
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple


class ReportValidationError(Exception):
    """Raised when a built report fails validation."""


@dataclass
class ReportResult:
    """Structured output so other agents/orchestrators can inspect it."""

    markdown: str
    mission: str
    sections_included: List[str] = field(default_factory=list)
    sections_dropped_as_duplicate: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    validated: bool = False


class ReportFormatterAgent:
    """Deterministic document-processing agent.

    Responsibilities:
        1. Accept raw AI markdown.
        2. Clean formatting noise.
        3. Parse report sections.
        4. Remove duplicate sections.
        5. Normalize headings to a canonical set.
        6. Preserve tables, lists, code blocks, and block quotes.
        7. Build one canonical report.
        8. Validate the report.
        9. Return the final markdown.

    It never generates new content -- it only reorganizes what already
    exists in the input.
    """

    AGENT_NAME = "ReportFormatterAgent"
    AGENT_ROLE = (
        "Deterministic document-processing agent that normalizes "
        "AI-generated mission reports into a canonical Markdown format."
    )

    # Canonical section order for the final report.
    CANONICAL_SECTIONS = [
        "Executive Summary",
        "Key Findings",
        "Risk Assessment",
        "Recommendations",
        "Conclusion",
    ]

    # Recognized heading text (normalized: lowercased, no trailing colon)
    # mapped to the canonical section it belongs to. First occurrence of
    # any synonym wins; later ones are treated as duplicates.
    SECTION_SYNONYMS: Dict[str, List[str]] = {
        "Executive Summary": [
            "executive summary",
            "summary",
            "overview",
        ],
        "Key Findings": [
            "key findings",
            "findings",
            "analysis",
            "results",
        ],
        "Risk Assessment": [
            "risk assessment",
            "risks",
            "risk analysis",
        ],
        "Recommendations": [
            "recommendations",
            "recommendation",
            "action plan",
        ],
        "Conclusion": [
            "conclusion",
            "next steps",
            "closing remarks",
        ],
    }

    SEPARATOR_RE = re.compile(r"^[-=_*]{3,}$")
    ATX_HEADING_RE = re.compile(r"^(#{1,6})\s*(.+?)\s*#*$")
    BOLD_LINE_RE = re.compile(r"^\*\*(.+?)\*\*:?$")
    CODE_FENCE_RE = re.compile(r"^```")
    MISSION_REPORT_TITLE_RE = re.compile(
        r"^#\s*mission report\s*$", re.IGNORECASE
    )

    FOOTER = "Generated by Agent Command Center"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def format(self, mission: str, raw_markdown: str) -> ReportResult:
        """Run the full pipeline and return a structured result."""

        warnings: List[str] = []

        cleaned = self._clean(raw_markdown or "")
        sections = self._extract_sections(cleaned)
        deduped, dropped = self._remove_duplicate_sections(sections)
        canonical_map, extra_sections = self._normalize_sections(deduped)

        if not canonical_map and not extra_sections:
            warnings.append("No recognizable sections were found in the input.")

        report = self._build_report(mission, canonical_map, extra_sections)

        try:
            self._validate(mission, canonical_map, extra_sections, report)
            validated = True
        except ReportValidationError as exc:
            warnings.append(str(exc))
            validated = False

        included = [c for c in self.CANONICAL_SECTIONS if canonical_map.get(c)]
        included += [title for title, _ in extra_sections]

        return ReportResult(
            markdown=report,
            mission=mission.strip() if mission else "",
            sections_included=included,
            sections_dropped_as_duplicate=dropped,
            warnings=warnings,
            validated=validated,
        )

    def handle(self, task: dict) -> dict:
        """Agent-message style entry point for use by an orchestrator.

        Accepts either:
            {"mission": ..., "raw_markdown": ...}
        or the legacy shape:
            {"mission": ..., "summary": ..., "findings": ..., "recommendations": ...}

        Returns a plain dict so it can be passed between agents without
        depending on this module's dataclasses.
        """

        mission = task.get("mission", "")

        if "raw_markdown" in task:
            raw_markdown = task["raw_markdown"]
        else:
            raw_markdown = self._assemble_raw_markdown(
                task.get("summary", ""),
                task.get("findings", ""),
                task.get("recommendations", ""),
            )

        result = self.format(mission, raw_markdown)

        return {
            "status": "ok" if result.validated else "warning",
            "markdown": result.markdown,
            "sections_included": result.sections_included,
            "sections_dropped_as_duplicate": result.sections_dropped_as_duplicate,
            "warnings": result.warnings,
            "agent": self.AGENT_NAME,
        }

    # ------------------------------------------------------------------
    # Step 1/2: Cleaning
    # ------------------------------------------------------------------

    def _clean(self, text: str) -> str:
        """Strip formatting noise while protecting fenced code blocks."""

        if not text:
            return ""

        text = text.replace("\r\n", "\n").replace("\r", "\n")

        protected, blocks = self._protect_code_blocks(text)

        lines = protected.split("\n")
        out_lines: List[str] = []
        blank_run = 0

        for line in lines:
            stripped = line.strip()

            # Drop separator-only lines (---, ===, ***, ___...). Table
            # separator rows (|---|---|) contain pipes and never match.
            if stripped and self.SEPARATOR_RE.match(stripped):
                continue

            # Drop any stray "# Mission Report" title the model added;
            # the agent adds its own canonical one.
            if self.MISSION_REPORT_TITLE_RE.match(stripped):
                continue

            if stripped == "":
                blank_run += 1
                if blank_run > 1:
                    continue
            else:
                blank_run = 0

            out_lines.append(line)

        cleaned = "\n".join(out_lines).strip()
        return self._restore_code_blocks(cleaned, blocks)

    def _protect_code_blocks(self, text: str) -> Tuple[str, List[str]]:
        """Replace fenced code blocks with placeholders so cleaning
        regexes never touch their contents."""

        blocks: List[str] = []

        def _stash(match: re.Match) -> str:
            blocks.append(match.group(0))
            return f"\x00CODEBLOCK{len(blocks) - 1}\x00"

        pattern = re.compile(r"```.*?```", re.DOTALL)
        protected = pattern.sub(_stash, text)
        return protected, blocks

    def _restore_code_blocks(self, text: str, blocks: List[str]) -> str:
        for index, block in enumerate(blocks):
            text = text.replace(f"\x00CODEBLOCK{index}\x00", block)
        return text

    # ------------------------------------------------------------------
    # Step 3: Section extraction
    # ------------------------------------------------------------------

    def _extract_sections(self, text: str) -> List[dict]:
        """Parse cleaned markdown into an ordered list of sections.

        Tables, bullet/numbered lists, code blocks, and block quotes
        are left untouched inside each section's body -- only heading
        lines are inspected.
        """

        sections: List[dict] = []
        current_heading: Optional[str] = None
        current_canonical: Optional[str] = None
        current_body: List[str] = []
        in_code_block = False

        def _flush():
            if current_heading is not None:
                sections.append(
                    {
                        "raw_heading": current_heading,
                        "canonical": current_canonical,
                        "body": "\n".join(current_body).strip("\n"),
                    }
                )

        for line in text.split("\n"):
            stripped = line.strip()

            if self.CODE_FENCE_RE.match(stripped):
                in_code_block = not in_code_block
                current_body.append(line)
                continue

            if not in_code_block:
                heading_text = self._match_heading(stripped)
                if heading_text is not None:
                    _flush()
                    current_heading = heading_text
                    current_canonical = self._canonicalize(heading_text)
                    current_body = []
                    continue

            # Preamble (content before the first heading) is not part
            # of any section and is discarded -- mission/date/etc are
            # supplied separately by the caller, so nothing meaningful
            # is lost.
            if current_heading is not None:
                current_body.append(line)

        _flush()
        return sections

    def _match_heading(self, line: str) -> Optional[str]:
        """Return heading text if a line looks like a heading, else None."""

        if not line:
            return None

        atx_match = self.ATX_HEADING_RE.match(line)
        if atx_match:
            return atx_match.group(2).strip()

        # Non-ATX headings (bold line, or a bare line) are only accepted
        # if they exactly match a known section synonym -- this avoids
        # mistaking ordinary prose for a heading.
        candidate = line
        bold_match = self.BOLD_LINE_RE.match(line)
        if bold_match:
            candidate = bold_match.group(1)

        normalized = candidate.strip().rstrip(":").lower()
        for synonyms in self.SECTION_SYNONYMS.values():
            if normalized in synonyms:
                return candidate.strip()

        return None

    def _canonicalize(self, heading_text: str) -> Optional[str]:
        normalized = heading_text.strip().rstrip(":").lower()
        for canonical, synonyms in self.SECTION_SYNONYMS.items():
            if normalized in synonyms:
                return canonical
        return None

    # ------------------------------------------------------------------
    # Step 4: Duplicate removal
    # ------------------------------------------------------------------

    def _remove_duplicate_sections(
        self, sections: List[dict]
    ) -> Tuple[List[dict], List[str]]:
        """Keep only the first occurrence of each section.

        Recognized (canonical) headings are deduplicated by canonical
        name. Unrecognized headings are kept but deduplicated by their
        own text, so nothing that isn't a true repeat gets dropped.
        """

        seen_canonical = set()
        seen_custom = set()
        result: List[dict] = []
        dropped: List[str] = []

        for section in sections:
            canonical = section["canonical"]

            if canonical:
                if canonical in seen_canonical:
                    dropped.append(section["raw_heading"])
                    continue
                seen_canonical.add(canonical)
                result.append(section)
            else:
                key = section["raw_heading"].strip().lower()
                if key in seen_custom:
                    dropped.append(section["raw_heading"])
                    continue
                seen_custom.add(key)
                result.append(section)

        return result, dropped

    # ------------------------------------------------------------------
    # Step 5: Normalization
    # ------------------------------------------------------------------

    def _normalize_sections(
        self, sections: List[dict]
    ) -> Tuple[Dict[str, str], List[Tuple[str, str]]]:
        """Map deduplicated sections onto the canonical structure.

        Empty sections are omitted entirely -- the agent never
        fabricates content to fill a gap.
        """

        canonical_map: Dict[str, str] = {}
        extra_sections: List[Tuple[str, str]] = []

        for section in sections:
            body = section["body"].strip("\n").strip()
            if not body:
                continue

            if section["canonical"]:
                canonical_map[section["canonical"]] = body
            else:
                extra_sections.append((section["raw_heading"].strip(), body))

        return canonical_map, extra_sections

    # ------------------------------------------------------------------
    # Step 6/7: Report building
    # ------------------------------------------------------------------

    def _build_report(
        self,
        mission: str,
        canonical_map: Dict[str, str],
        extra_sections: List[Tuple[str, str]],
    ) -> str:
        separator = "=" * 60
        generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        blocks: List[str] = [
            "# Mission Report",
            f"Mission\n-------\n{(mission or '').strip()}",
            f"Generated\n---------\n{generated}",
            "Generated By\n------------\n"
            "Agent Command Center\nWriter Agent\nReport Formatter",
        ]

        for canonical in self.CANONICAL_SECTIONS:
            body = canonical_map.get(canonical)
            if body:
                blocks.append(separator)
                blocks.append(f"# {canonical}\n\n{body}")

        for title, body in extra_sections:
            blocks.append(separator)
            blocks.append(f"# {title}\n\n{body}")

        blocks.append(separator)
        blocks.append(self.FOOTER)

        return "\n\n".join(blocks).strip() + "\n"

    # ------------------------------------------------------------------
    # Step 8: Validation
    # ------------------------------------------------------------------

    def _validate(
        self,
        mission: str,
        canonical_map: Dict[str, str],
        extra_sections: List[Tuple[str, str]],
        report: str,
    ) -> bool:
        errors: List[str] = []

        if not mission or not mission.strip():
            errors.append("Mission is required but was empty.")

        if not canonical_map and not extra_sections:
            errors.append("At least one report section is required.")

        if not report or not report.strip():
            errors.append("Final report output is empty.")

        if errors:
            raise ReportValidationError("; ".join(errors))

        return True

    # ------------------------------------------------------------------
    # Legacy support
    # ------------------------------------------------------------------

    def _assemble_raw_markdown(
        self, summary: str, findings: str, recommendations: str
    ) -> str:
        """Combine the old four-piece call shape into one raw markdown
        blob so it can flow through the same pipeline as everything
        else."""

        parts = []
        if summary:
            parts.append(f"# Executive Summary\n\n{summary}")
        if findings:
            parts.append(f"# Key Findings\n\n{findings}")
        if recommendations:
            parts.append(f"# Recommendations\n\n{recommendations}")
        return "\n\n".join(parts)


# Backwards-compatible alias for existing imports of `ReportFormatter`.
ReportFormatter = ReportFormatterAgent

formatter = ReportFormatterAgent()


def format_report(
    mission: str,
    raw_report: str = None,
    summary: str = None,
    findings: str = None,
    recommendations: str = None,
) -> str:
    """Formats a mission report into the canonical markdown structure.

    Preferred usage -- the Writer Agent produces one narrative report
    containing all of its sections, and this is passed straight through:

        format_report(mission, raw_report)

    Legacy usage is still supported for any existing callers that pass
    the report as three separate pieces:

        format_report(mission, summary=..., findings=..., recommendations=...)
    """

    if raw_report is None:
        raw_report = formatter._assemble_raw_markdown(
            summary or "", findings or "", recommendations or ""
        )

    return formatter.format(mission, raw_report).markdown