import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { FileText } from "lucide-react";
import PageHeader from "../components/common/PageHeader";
import LoadingRow from "../components/common/LoadingRow";
import EmptyState from "../components/common/EmptyState";
import ErrorState from "../components/common/ErrorState";
import ReportRow from "../components/reports/ReportRow";
import ReportPreview from "../components/reports/ReportPreview";
import { useFetch } from "../hooks/useFetch";
import { reportsApi } from "../api/client";
import { getReportId } from "../utils/report";

export default function Reports() {
  const { data: reports, loading, error, refetch } = useFetch(() => reportsApi.list(), []);
  const [searchParams] = useSearchParams();
  const [selectedId, setSelectedId] = useState(searchParams.get("mission"));

  useEffect(() => {
    if (!selectedId && reports?.length) setSelectedId(getReportId(reports[0]));
  }, [reports, selectedId]);

  const selected = reports?.find((r) => getReportId(r) === selectedId);

  return (
    <>
      <PageHeader title="Reports" description="Executive summaries and recommendations generated by the Writer agent after each mission completes." />

      {loading ? (
        <LoadingRow label="Loading reports…" />
      ) : error ? (
        <ErrorState error={error} onRetry={refetch} label="Couldn't load reports" />
      ) : !reports?.length ? (
        <EmptyState icon={<FileText size={18} />} title="No reports yet" message="Reports appear here once a mission finishes." />
      ) : (
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1.2fr", gap: 16 }} className="dashboard-grid">
          <div className="row-list">
            {reports.map((r) => (
              <ReportRow
                key={getReportId(r)}
                report={r}
                active={getReportId(r) === selectedId}
                onClick={() => setSelectedId(getReportId(r))}
              />
            ))}
          </div>
          <ReportPreview report={selected} />
        </div>
      )}
    </>
  );
}
